name: CI-coverage

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
          php_version: 7.4
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
